### PR TITLE
chore: enable smart contract ci

### PR DESCRIPTION
**Pull request by aahna-ashina**
https://app.dework.xyz/nation3/develop-1?taskId=e23d172b-e1d5-40cc-ba4c-6818c02d7f35

### CODE REVIEW

**Review by johnmark13 — APPROVED** [review]

**Comment by gregfromstl** [comment]
Just double checking you've run this workflow on another branch to confirm it works?

**Review by gregfromstl — APPROVED** [review]

**Comment by aahna-ashina** [comment]
> Just double checking you've run this workflow on another branch to confirm it works?

@gregfromstl Yes, the workflows have been run on _this_ branch.  If you press the green checkmark, you'll see an overview of all the GitHub Action status checks:

Screen Shot 2022-07-22 at 9 42 47 AM

And if you press "Details", you should be able to see the log output as well:

Screen Shot 2022-07-22 at 9 45 31 AM

**Comment by gregfromstl** [comment]
Oof I'm dumb. Looks good.

**Review by luisivan — APPROVED** [review]

**Review by xPi2 — APPROVED** [review]
LGTM

**Pull request merged**
