### PR TITLE
Fix yarn lint warnings

### PR DESCRIPTION
**Pull request by southbears**
Task details: https://app.dework.xyz/nation3/citizen-app-p?taskId=169960b2-e749-44fc-8553-c1f409b84a32

### CODE REVIEW

**Comment by johnmark13** [comment]
Are you sure that you want to add all these new triggers? Mostly look innocuous, but not sure they should be added, for example the constant in ui/lib/use-preferred-network.ts .

**Review by xPi2 — CHANGES_REQUESTED** [review]
I'm experiencing problems with lock inputs, both amount and end date are not responding to any attempt of changing them.

**Comment by southbears** [comment]
> Are you sure that you want to add all these new triggers? Mostly look innocuous, but not sure they should be added, for example the constant in ui/lib/use-preferred-network.ts .

Yea, you're right. I've removed some of the places (most notably `useStaticCall`) where I'm not really sure if it's safe to add new deps. The other places seem OK to me, but please point out which ones you'd be worried about.

> I'm experiencing problems with lock inputs, both amount and end date are not responding to any attempt of changing them.

This has been fixed. `oneWeekOut` wasn't memoized, causing the effect to be triggered all the time

---

In general I'd be vary of making stuff so effect driven. It's often difficult to follow the logic and it's easy to get into trouble by creating effects that trigger unexpectedly or get stuck in infinite loops (like the unmemoized `oneWeekOut` problem above)

**Comment by xPi2** [comment]
Still having no luck with lock inputs. Could be an error on my end?

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
I tested on https://app-ldpuma3in-nation3.vercel.app/lock, and I'm not able to adjust the number in the "Lock amount" field:

> Screen Shot 2022-08-04 at 7 48 53 PM

For comparison, I tried adjusting the number at https://app.nation3.org/lock, which worked fine:

> Screen Shot 2022-08-04 at 7 49 07 PM

**Comment by southbears** [comment]
@aahna-ashina @xPi2 it seems like the Vercel build above is 21h old (from the first commit) and hasn't been regenerated from the changes I made (19h ago). Is there a way to make Vercel regenerate a build? Alternatively, test this locally and it should work as expected.

**Comment by aahna-ashina** [comment]
> it seems like the Vercel build above is 21h old (from the first commit) and hasn't been regenerated from the changes I made (19h ago). Is there a way to make Vercel regenerate a build?

I think the Vercel deployment at https://app-ldpuma3in-nation3.vercel.app/ was for the most recent commit: https://github.com/nation3/app/pull/67/commits/48582145fa20a8265c51c86be95490a7f540f826

> Screen Shot 2022-08-05 at 7 07 59 PM

And if there will be more commits, a new Vercel deployment should trigger on a different URL.  If that's the case, please let me know so we can fix the problem.

**Comment by aahna-ashina** [comment]
> Alternatively, test this locally and it should work as expected.

@southbears I tested this branch locally at http://localhost:42069/lock, and I'm not able to adjust the lock amount there either.  If I try typing a number, the input field does not react:

> Screen Shot 2022-08-05 at 7 12 07 PM

I'm also seeing these errors:
```typescript
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at ActionNeedsTokenApproval (webpack-internal:///./components/ActionNeedsTokenApproval.tsx:25:27)
    at ActionButton (webpack-internal:///./components/ActionButton.tsx:81:27)
    at div
    at div
    at div
    at div
    at div
    at div
    at div
    at MainCard (webpack-internal:///./components/MainCard.tsx:12:26)
    at Lock (webpack-internal:///./pages/lock.tsx:99:74)
    at div
    at div
    at PreferredNetworkWrapper (webpack-internal:///./components/PreferredNetworkWrapper.tsx:19:26)
    at div
    at div
    at div
    at div
    at div
    at PassportCheck (webpack-internal:///./components/PassportCheck.tsx:15:26)
    at Layout (webpack-internal:///./components/Layout.tsx:139:26)
    at ErrorProvider (webpack-internal:///./components/ErrorProvider.tsx:80:26)
    at NftProvider2 (webpack-internal:///./node_modules/use-nft/dist/use-nft.es.js:1422:3)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/lib/reactjs/QueryClientProvider.mjs:46:3)
    at WagmiConfig (webpack-internal:///./node_modules/wagmi/dist/wagmi.esm.js:262:5)
    at App (webpack-internal:///./pages/_app.tsx:54:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:357:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:791:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:915:27)
```

**Review by aahna-ashina — CHANGES_REQUESTED** [review]
When testing locally, lock amount cannot be changed:  https://github.com/nation3/app/pull/67#issuecomment-1206333537

**Comment by southbears** [comment]
@aahna-ashina can you still repro this on the latest Vercel build? It's working properly for me here: https://app-git-fork-southbears-southbear-dw-339fix-yarn-1afa07-nation3.vercel.app/lock

Also, when you've been testing this, are you 100% sure it was on https://github.com/nation3/app/pull/67/commits/48582145fa20a8265c51c86be95490a7f540f826 or https://github.com/nation3/app/pull/67/commits/c3cc9bec55fbc8cab5c1d4d26bc6cf5d04c1e6c3? Sorry for potentially asking a dumb question, but the reason is that the problems you're describing should have been fixed by https://github.com/nation3/app/pull/67/commits/48582145fa20a8265c51c86be95490a7f540f826

**Comment by xPi2** [comment]
@southbears I think the problem is that it works for you because it works when you don't have already a lock in place but when you have one it does't let you update the values. If you want to test it on goerli I can send you some goerli NATION to try it out by yourself.

**Comment by southbears** [comment]
@xPi2 @aahna-ashina I see now. Really sorry about all the back n forth here - this is a wild outlier from my POV in amount of back and forth. I'm expecting you to not have to spend so much time on me with back n forths in the future

This is what I've tested now:
* Connected (to mainnet where I have locked tokens) and changed slider/input in /lock page
* Disconnected and changed slider/input in /lock page
* Input on liquidity rewards page (both when connected and not)

It's working as intended on the latest Vercel deployment (https://app-l5e2dw1nl-nation3.vercel.app/) based on my testing

Some other observations:
* Lots of components have untyped props => makes it harder to understand what's going on
* A lot of variables are not memoized, which is what caused this latest problem. Ideally the frontend shouldn't be as `useEffect` driven as it is now. Rather than storing something in state in an effect hook, we should memoize variables with `useMemo`

**Comment by xPi2** [comment]
I'm not a frontend expert so I'm not very aware of the quality of the frontend code from an experienced perspective. Anyways I understand that memoization would also help with general performance of the app so I think your suggestions are very on point. Let's develop them into additional tasks!

**Review by xPi2 — APPROVED** [review]
Working on my side now. All changes look great!

**Review by aahna-ashina — APPROVED** [review]

**Comment by gregfromstl** [comment]
Going to merge this before it becomes stale.

**Pull request merged**
