### PR TITLE
feat(lock): Limit the allowance for veNATION transfers

### PR DESCRIPTION
**Pull request by xPi2**
This is not related to any task in specific.
If anyone want more context feel free to DM.

## Screenshots (if appropriate):

Screenshot 2022-10-31 at 16 48 28

## How Has This Been Tested?

Running UI on local with goerli tesnet.

### CODE REVIEW

**Comment by xPi2** [comment]
@aahna-ashina I don't understand why the build fails on the cypress tests if the project is built correctly in vercel preview

**Comment by johnmark13** [comment]
There is an issue connecting the a node, as there is no Infura config in the .env.goerli file could it just be point in time?

**Review by luisivan — APPROVED** [review]

**Review by pythonpete32 — APPROVED** [review]

**Comment by xPi2** [comment]
> PR looks good. It would be easier to read if the code style changes were in a separate commit so that the functional change/s could be viewed in isolation, but that is a small thing.

I always run prettier before commiting and apparently no one had done it in a while. So the autoformatter has formatted the full file.

**Comment by xPi2** [comment]
> No allowUnlimited now, any issues with it?

Safety concerns

**Comment by aahna-ashina** [comment]
> I don't understand why the build fails on the cypress tests if the project is built correctly in vercel preview

@xPi2 Are you saying that the integration tests passed when you ran them locally on your computer?

**Comment by xPi2** [comment]
> @xPi2 A Vercel preview does not include integration testing; Only building and deployment. Are you saying that the Cypress integration tests passed when you ran them [locally](https://github.com/nation3/app/tree/main/ui#integration-testing) on your computer?

The error doesn't seem to have anything to do with the test itself, it says it's an "unhandled promise rejection" from the code. I'm not able to replicate it neither on local, preview or the now in production deployment.

Could you or someone from the Developer guild take a look at it?

**Pull request merged**
