### PR TITLE
Upgrade wagmi from 0.4.x

### PR DESCRIPTION
**Pull request by Caranell**
## Dework Task

https://app.dework.xyz/nation3/app-2?taskId=3f43dfb0-5d88-460a-b391-a4d72aa8dab4

## How Has This Been Tested?

Manually checked that data on page (which uses `useReadContract`) & write functions (`useWriteContract`) work properly.

### CODE REVIEW

**Comment by Caranell** [comment]
I tried to group changes to different functions in separate commits and was going from top to bottom of this page (https://wagmi.sh/docs/migration-guide#05x-breaking-changes), in case anyone wants to check the correctness of the changes :)

**Comment by aahna-ashina** [comment]
@xPi2 Could you check why the Vercel deployment failed?

**Comment by aahna-ashina** [comment]
@xPi2 Anything in the Vercel log?

**Comment by luisivan** [comment]
@aahna-ashina super weird. Just `An internal error occurred with Vercel.`...

**Comment by luisivan** [comment]
@aahna-ashina @Caranell god knows what happened, it seems to have worked now

**Comment by aahna-ashina** [comment]
> super weird. Just `An internal error occurred with Vercel.`...

@luisivan Nothing under the "Errors" tab either?

> Screen Shot 2022-09-06 at 6 50 56 PM

**Comment by luisivan** [comment]
@aahna-ashina no, they don't get stored (they would appear only if you are checking that tab the time the error throws)

**Comment by aahna-ashina** [comment]
> Manually checked that data on page (which uses `useReadContract`) & write functions (`useWriteContract`) work properly.

@Caranell Thank you for doing this upgrade.  I tested your changes on Goerli, where I was able to make an on-chain transaction for increasing the lock amount at http://localhost:42069/lock.  I failed to deposit pool tokens at http://localhost:42069/liquidity, but I'm having the same problem on the `main` branch so I think that's a pre-existing bug we will have to solve separately.  So will approve your code changes 😄

**Review by aahna-ashina — APPROVED** [review]

**Comment by aahna-ashina** [comment]
@Caranell Could you check the merge conflict?

**Comment by Caranell** [comment]
@aahna-ashina Yea, I'll check, though I'd ask someone to review & merge this PR, as it changes lots of files and subtle to get more merge conflicts

**Review by pythonpete32 — APPROVED** [review]

**Review by aahna-ashina — APPROVED** [review]

**Pull request merged**
