### PR TITLE
test: add jest

### PR DESCRIPTION
**Pull request by aahna-ashina**
## Dework Task

https://app.dework.xyz/nation3/develop-1?taskId=eb9bf3fd-df91-443d-a950-2e4e75dcfd4a

## How Has This Been Tested?

```
yarn test
```
```typescript
yarn run v1.22.19
$ jest
 PASS  lib/network-id.test.ts (17.499 s)
 PASS  lib/numbers.test.ts (18.102 s)

Test Suites: 2 passed, 2 total
Tests:       6 passed, 6 total
Snapshots:   0 total
Time:        19.193 s
Ran all test suites.
✨  Done in 21.52s.
```

### CODE REVIEW

**Review by johnmark13 — COMMENTED** [review]
Great! Are you sure that you want to have the __tests__ folder though and not colocate the tests with the source code?

**Comment by aahna-ashina** [comment]
> Great! Are you sure that you want to have the **tests** folder though and not colocate the tests with the source code?

@johnmark13 I'm not sure 😃

What would you recommend as a best-practice?

**Comment by johnmark13** [comment]
> @johnmark13 I'm not sure 😃
> 
> What would you recommend as a best-practice?

I think it is a very opinionated i.e, there is no right or wrong. Most commonly now I see unit tests being in the same folder as the code they are testing. Integration tests being in dedicated test folders.

**Comment by aahna-ashina** [comment]
@johnmark13 Implemented your suggestion:  5a8fe9ab325e718e6e9cdb2b727e6b9ca7a6b9e5

**Review by johnmark13 — APPROVED** [review]

**Review by luisivan — APPROVED** [review]

**Pull request merged**
