### PR TITLE
Migrate to TS

### PR DESCRIPTION
**Pull request by gregfromstl**
Changes:
- Used `ts-migrate` to begin migration to typescript
- Removed a million and one `// @ts-expect-error` comments from `ts-migrate`
- Upgraded `next` to fix typescript error
- Fixed bugs caused by TS

### CODE REVIEW

**Review by luisivan — CHANGES_REQUESTED** [review]
Awesome!

Few issues:
- Unknown error when in Claim page
Screen Shot 2022-05-19 at 12 00 40 PM
- In the Lock page, there should be a space between _Available to lock_ and the amount
- Also both Lock Amount and the final balance calculation seem to always show 0
Screen Shot 2022-05-19 at 12 01 11 PM
- Liquidity fails with a TypeError (`BigNumber.isZero`, looks like)
- When wallet is not connected yet, it thinks the user is on the wrong network
Screen Shot 2022-05-19 at 12 03 33 PM

**Comment by luisivan** [comment]
- Reproducing the 0 values (then once the user interacts, it shows correct ones):

- When opening the Liquidity page, it shows correctly for a second and then crashes with this:
Screen Shot 2022-05-19 at 8 08 41 PM

**Review by aahna-ashina — COMMENTED** [review]
At https://app-3lsnp8xfg-nation3.vercel.app/liquidity there is a `HTTP 401` error in the console. Not sure if this is related to the refactoring, though.

Screen Shot 2022-05-20 at 11 23 01 AM

**Review by aahna-ashina — COMMENTED** [review]
Getting an application error when visiting https://app-3lsnp8xfg-nation3.vercel.app/liquidity without being connect with a wallet:

Screen Shot 2022-05-20 at 11 26 18 AM

Screen Shot 2022-05-20 at 11 25 55 AM

**Comment by gregfromstl** [comment]
> At https://app-3lsnp8xfg-nation3.vercel.app/liquidity there is a `HTTP 401` error in the console. Not sure if this is related to the refactoring, though.
> 
> 
> 
> Screen Shot 2022-05-20 at 11 23 01 AM

To my knowledge this was preexisting

**Comment by gregfromstl** [comment]
> Getting an application error when visiting https://app-3lsnp8xfg-nation3.vercel.app/liquidity without being connect with a wallet:
> 
> 
> 
> > Screen Shot 2022-05-20 at 11 26 18 AM
> 
> 
> 
> > Screen Shot 2022-05-20 at 11 25 55 AM
> 
> 

Yeah this is a known issue

**Comment by luisivan** [comment]
Hey @gregfromstl! It seems like everything has been fixed, except I'm still seeing 0.00% as my boosted APY.

**Review by aahna-ashina — COMMENTED** [review]
@gregfromstl The _Rewards APY_ is not loading: https://app-qd7j6o509-nation3.vercel.app/liquidity

Screen Shot 2022-05-24 at 12 09 32 PM

```
Provider: Connected to the user's provider on chain with ID 1
```
```javascript
3_app-f19f1fb3f41db82c.js:1 Uncaught (in promise) Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.6.1)
    at d.makeError (_app-f19f1fb3f41db82c.js:1:107069)
    at d.throwError (_app-f19f1fb3f41db82c.js:1:107189)
    at d.throwArgumentError (_app-f19f1fb3f41db82c.js:1:107244)
    at _app-f19f1fb3f41db82c.js:1:63667
    at Generator.next (<anonymous>)
    at s (_app-f19f1fb3f41db82c.js:1:63147)
```

**Comment by gregfromstl** [comment]
@aahna-ashina could you connect your wallet and try? It won't load if it doesn't have a wallet address to pass to the contract.

**Comment by aahna-ashina** [comment]
> @aahna-ashina could you connect your wallet and try? It won't load if it doesn't have a wallet address to pass to the contract.

@gregfromstl Yes, it works when connected with an account.

**Pull request merged**
